### ISSUE TITLE
Texture Path in emitter.json

### ISSUE THREAD

**Issue by SeminYun** [CloudKidStudio/PixiParticlesEditor#6]
hi.

PIXiPartclesEditor don't add Textures into Emitter.json

is there any reason?

 i can add manually into code 

but i don't want it becuase other member handle this and control

so i or we want to add texture's path or filename  into json

is this possible?

thx a lot

**Comment by andrewstart** [comment]
[Release 1.5.0 of PixiParticles](https://github.com/CloudKidStudio/PixiParticles/releases/tag/1.5.0) allows you to use strings instead of Texture instances. We won't be including that in the emitter json however, because where you place your textures, and potentially how you load them, is entirely up to your project and has nothing to do with the tool.
